```yaml
apiVersion: apps/v1
kind: Deployment

metadata:
  name: streaming

spec:
  replicas: {{ .Values.services.streaming.replicas }}

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: streaming

  template:
    metadata:
      labels:
        app: streaming

    spec:
      containers:
        - name: streaming

          image: "{{ .Values.services.streaming.image }}:{{ .Values.services.streaming.tag }}"

          imagePullPolicy: {{ .Values.services.streaming.imagePullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.services.streaming.port }}
              protocol: TCP

          envFrom:
            - configMapRef:
                name: streamingapp-config

            - secretRef:
                name: streamingapp-secret

          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
