apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamingapp-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamingapp-admin
  template:
    metadata:
      labels:
        app: streamingapp-admin
    spec:
      containers:
        - name: admin
          image: "{{ .Values.services.admin.image.repository }}:{{ .Values.services.admin.image.tag }}"
          imagePullPolicy: "{{ .Values.services.admin.image.pullPolicy }}"
          ports:
            - containerPort: 3003
          env:
            - name: PORT
              value: "3003"
            - name: MONGO_URI
              value: "mongodb://mongo.streaming.svc.cluster.local:27017/{{ .Values.mongo.database }}"
            - name: JWT_SECRET
              value: "changeme"
            - name: CLIENT_URLS
              value: "http://k8s-streamin-streamin-1160eeb89c-1828266227.ap-south-1.elb.amazonaws.com"

---
apiVersion: v1
kind: Service
metadata:
  name: admin
spec:
  type: ClusterIP
  selector:
    app: streamingapp-admin
  ports:
    - port: 3003
      targetPort: 3003

