apiVersion: apps/v1
kind: Deployment

metadata:
  name: admin

spec:
  replicas: {{ .Values.services.admin.replicas }}

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: admin

  template:
    metadata:
      labels:
        app: admin

    spec:
      containers:
        - name: admin
          image: "{{ .Values.services.admin.image }}:{{ .Values.services.admin.tag }}"

          ports:
            - containerPort: {{ .Values.services.admin.port }}

          envFrom:
            - configMapRef:
                name: streamingapp-config
            - secretRef:
                name: streamingapp-secret

          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.services.admin.port }}
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.services.admin.port }}
            initialDelaySeconds: 30
            periodSeconds: 20