apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:

  replicas: {{ .Values.services.auth.replicas }}

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: auth

  template:
    metadata:
      labels:
        app: auth

    spec:
      containers:
        - name: auth
          image: "{{ .Values.services.auth.image }}:{{ .Values.services.auth.tag }}"

          ports:
            - containerPort: {{ .Values.services.auth.port }}

          envFrom:
            - configMapRef:
                name: streamingapp-config

            - secretRef:
                name: streamingapp-secret

          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.services.auth.port }}
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.services.auth.port }}
            initialDelaySeconds: 30
            periodSeconds: 20