apiVersion: v1
kind: Service

metadata:
  name: chat-svc

spec:
  selector:
    app: chat

  ports:
    - protocol: TCP
      port: 3004
      targetPort: {{ .Values.services.chat.port }}

  type: ClusterIP