pipeline {

    agent any

    environment {
        AWS_REGION = 'ap-south-1'
        AWS_ACCOUNT_ID = 'YOUR_AWS_ACCOUNT_ID'
        ECR_REGISTRY = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Images') {
            steps {

                sh '''
                docker build -t streaming-auth:1.0.0 backend/authService

                docker build -t streaming-stream:1.0.0 \
                -f backend/streamingService/Dockerfile backend

                docker build -t streaming-admin:1.0.0 \
                -f backend/adminService/Dockerfile backend

                docker build -t streaming-chat:1.0.0 \
                -f backend/chatService/Dockerfile backend

                docker build -t streaming-frontend:1.0.0 frontend
                '''
            }
        }

        stage('Login to ECR') {
            steps {
                sh '''
                aws ecr get-login-password \
                --region ${AWS_REGION} | \
                docker login \
                --username AWS \
                --password-stdin ${ECR_REGISTRY}
                '''
            }
        }

        stage('Push Images') {
            steps {

                sh '''
                docker tag streaming-auth:1.0.0 \
                ${ECR_REGISTRY}/streaming-auth:1.0.0

                docker tag streaming-stream:1.0.0 \
                ${ECR_REGISTRY}/streaming-stream:1.0.0

                docker tag streaming-admin:1.0.0 \
                ${ECR_REGISTRY}/streaming-admin:1.0.0

                docker tag streaming-chat:1.0.0 \
                ${ECR_REGISTRY}/streaming-chat:1.0.0

                docker tag streaming-frontend:1.0.0 \
                ${ECR_REGISTRY}/streaming-frontend:1.0.0

                docker push ${ECR_REGISTRY}/streaming-auth:1.0.0
                docker push ${ECR_REGISTRY}/streaming-stream:1.0.0
                docker push ${ECR_REGISTRY}/streaming-admin:1.0.0
                docker push ${ECR_REGISTRY}/streaming-chat:1.0.0
                docker push ${ECR_REGISTRY}/streaming-frontend:1.0.0
                '''
            }
        }
    }
}