apiVersion: v1
kind: Secret
metadata:
  name: streamingapp-secret
type: Opaque
stringData:
  JWT_SECRET: "6xWQmR3SN6vUWw198Jgr9JcJZ97Gv4ETvJCBVnvvBgA="
 AWS_ACCESS_KEY_ID=YOUR_AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY=YOUR_AWS_SECRET_ACCESS_KEY